-language: php
-php:
-  - '7.0'
-  - '7.1'
-
-script:
-   - composer install
-   - vendor/bin/phpunit
-services:
  - mysql
test:
  adapter: mysql2
  database: symfonyDemoApp
  username: root
  encoding: utf8

before_install:
  - mysql -e 'CREATE DATABASE symfonyDemoApp;'