# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        oauth.provider.github:
            id: AuthenticatorSandboxBundle\Security\GithubProvider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            simple_preauth:
                authenticator: AuthenticatorSandboxBundle\Security\GithubAuthenticator
            provider: oauth.provider.github


            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    access_control:
            # require ROLE_ADMIN for /admin*
            - { path: ^/admin, roles: ROLE_ADMIN }
