# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        oauth.provider.github:
            id: github_provider
        our_users:
            entity: { class: AuthenticatorSandboxBundle\Entity\User, property: username }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/admin/
            stateless: false
            simple_preauth:
                authenticator: github_authenticator
            provider: oauth.provider.github

        default:
            anonymous: ~
            guard:
                 authenticator:
                     - app.security.login_form_authenticator
            provider: our_users

            logout:
                path: /logout


            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    access_control:
          #- { path: ^/admin }
